### ISSUE TITLE
Disaster Data dashboard not displaying data

### ISSUE THREAD

**Issue by bramverweij** [idmc-labs/aisa-report#2]
FYI @AdityaKhatri 

**Please describe issue.**
On the [Disaster Displacement in Asia and the Pacific](https://www.internal-displacement.org/disaster-displacement-in-asia-and-the-pacific-2022) the "Disaster Data" dashboard is not displaying any data nor the graphs to accompany the data. The "Download Disaster Data" is also not working and leads to the [following page](https://gidd-idmc.dev.datafriendlyspace.org/api/countries/multiple-countries-disaster-export/?countries_iso3=AFG,ASM,ARM,AUS,AZE,BGD,BTN,BRN,KHM,CXR,CCK,COK,PRK,FSM,FJI,PYF,GEO,GUM,HMD,HKG,IND,IDN,JPN,KAZ,KIR,KGZ,LAO,MAC,MYS,MDV,MHL,MNG,MMR,NRU,NPL,NCL,NZL,NIU,NFK,MNP,PAK,PLW,PNG,CHN,PHL,PCN,KOR,WSM,SGP,SLB,LKA,TWN,TJK,THA,TLS,TKL,TON,TUR,TKM,TUV,UMI,UZB,VUT,VNM,WLF&start_year=2010&end_year=2021&hazard_type=). Please see screenshots [here](https://drive.google.com/drive/folders/1UFvYecRBfiTPoq9kjYz2TEDGMOIOsd05?usp=sharing). 

**Describe the solution you'd like**
Please remedy/revert this so that it works as previously.

**Describe alternatives you've considered**
N/A

**Additional Context**
N/A

**Comment by AdityaKhatri** [comment]
Hi @bramverweij , thanks for posting this issue.
We've worked on it partially, and its fix is hinged on the deployment of Helix's latest version.

This will be fixed and deployed by EOD tomorrow.
